#! /bin/sh

nitrogen --restore &
$HOME/.config/polybar/launch.sh &
blueman-tray &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
xrdb -merge ~/.Xresources &
picom --config ~/.config/picom.conf &
